const products = [
  {
    id: 101,
    src: require('../images/thums up.jpg'),
    name: 'Thums Up',
    price: 'INR 90',
    priceInt:90,
    image: '../images/thums up.jpg',
    category: 'grocery',
    description: 'Thumsup Diet Can (300 ml)',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
  {
    id: 102,
    src: require('../images/CokeCan.jpg'),
    name: 'COKE',
    price: 'INR 35',
    priceInt:35,
    image: '',
    category: 'grocery',
    description: 'Coca-Cola Diet Can (300 ml)',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
  {
    id: 103,
    src: require('../images/pepsi.jpg'),
    name: 'pepsi',
    price: 'INR 40',
    priceInt:40,
    image: '',
    category: 'grocery',
    description: 'Pepsi Can (300 ml)',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
  {
    id: 104,
    src: require('../images/frooty.jpg'),
    name: 'Fruity',
    price: 'INR 35',
    priceInt:35,
    image: '',
    category: 'grocery',
    description: 'Fruity Can (300 ml)',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
  {
    id: 105,
    src: require('../images/slice.jpg'),
    name: 'Slice',
    price: 'INR 35',
    priceInt:35,
    image: '',
    category: 'grocery',
    description: 'Slice Can (300 ml)',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
  {
    id: 106,
    src: require('../images/maaza.jpg'),
    name: 'Maaza',
    price: 'INR 95',
    priceInt:95,
    image: '',
    category: 'grocery',
    description: 'Maaza Bottle (2 litres)',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
  {
    id: 107,
    src: require('../images/red bull.jpg'),
    name: 'Red bull',
    price: 'INR 50',
    priceInt:50,
    image: '',
    category: 'grocery',
    description: 'Redbull Can (300 ml)',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
  {
    id: 108,
    src: require('../images/energy drinks.jpg'),
    name: 'Energy drinks',
    price: 'INR 60',
    priceInt:60,
    image: '',
    category: 'grocery',
    description: 'Energy drinks Can (300 ml)',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
  {
    id: 109,
    src: require('../images/alvino rocking chair.jpg'),
    name: 'Alvino Rocking Chair',
    price: 'INR 300',
    priceInt:300,
    image: '../images/alvino rocking chair.jpg',
    category: 'furniture',
    description: 'alvino rocking chair light weight',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
  {
    id: 110,
    src: require('../images/6 seater chair.jpg'),
    name: '6 seater chair',
    price: 'INR 700',
    priceInt:700,
    image: '',
    category: 'furniture',
    description: '6 seater chair(Family time)',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
  {
    id: 111,
    src: require('../images/kitchen chair.jpg'),
    name: 'Kitchen Chair',
    price: 'INR 250',
    priceInt:250,
    image: '',
    category: 'furniture',
    description: 'kitchen chair relaxing',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
  {
    id: 112,
    src: require('../images/novia chair.jpg'),
    name: 'Novia chair',
    price: 'INR 300',
    priceInt:300,
    image: '',
    category: 'furniture',
    description: 'novia chair (normal chair)',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
  {
    id: 113,
    src: require('../images/rocking chair.jpg'),
    name: 'Rocking Chair',
    price: 'INR 350',
    priceInt:350,
    image: '',
    category: 'furniture',
    description: 'rocking chair light weight',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
  {
    id: 114,
    src: require('../images/wooden chair.jpg'),
    name: 'Wooden Chair',
    price: 'INR 150',
    priceInt:150,
    image: '',
    category: 'furniture',
    description: 'wooden chair',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
  {
    id: 115,
    src: require('../images/plastic chair.jpg'),
    name: 'Plastic Chair',
    price: 'INR 150',
    priceInt:150,
    image: '',
    category: 'furniture',
    description: 'Plastic chair',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
  {
    id: 116,
    src: require('../images/wooden dininig chair.jpg'),
    name: 'Wooden Chair',
    price: 'INR 320',
    priceInt:320,
    image: '',
    category: 'furniture',
    description: 'wooden dininig chair best chair',
    discount_price: 2000,
    unit: 'per piece',
    orderedQty: 0,
    addButtonDisplay: 'inline-flex',
    qtyDisplay: 'none',
  },
];

export { products };
