const products = [
  {
    id: 1,
    src: require('../images/thums up.jpg'),
    name: 'Thums Up',
    price: 'INR 90',
    image: '../images/thums up.jpg',
    category: 'covid',
    description: 'Thumsup Diet Can (300 ml)',
    discount_price: 2000,
  },
  {
    id: 2,
    src: require('../images/CokeCan.jpg'),
    name: 'COKE',
    price: 'INR 35',
    image: '',
    category: 'covid',
    description: 'Coca-Cola Diet Can (300 ml)',
    discount_price: 2000,
  },
  {
    id: 3,
    src: require('../images/pepsi.jpg'),
    name: 'pepsi',
    price: 'INR 40',
    image: '',
    category: 'covid',
    description: 'Pepsi Can (300 ml)',
    discount_price: 2000,
  },
  {
    id: 4,
    src: require('../images/frooty.jpg'),
    name: 'Fruity',
    price: 'INR 35',
    image: '',
    category: 'covid',
    description: 'Fruity Can (300 ml)',
    discount_price: 2000,
  },
  {
    id: 5,
    src: require('../images/slice.jpg'),
    name: 'Slice',
    price: 'INR 35',
    image: '',
    category: 'covid',
    description: 'Slice Can (300 ml)',
    discount_price: 2000,
  },
  {
    id: 6,
    src: require('../images/maaza.jpg'),
    name: 'Maaza',
    price: 'INR 95',
    image: '',
    category: 'covid',
    description: 'Maaza Bottle (2 litres)',
    discount_price: 2000,
  },
  {
    id: 7,
    src: require('../images/red bull.jpg'),
    name: 'Red bull',
    price: 'INR 50',
    image: '',
    category: 'covid',
    description: 'Redbull Can (300 ml)',
    discount_price: 2000,
  },
  {
    id: 8,
    src: require('../images/energy drinks.jpg'),
    name: 'Energy drinks',
    price: 'INR 60',
    image: '',
    category: 'covid',
    description: 'Energy drinks Can (300 ml)',
    discount_price: 2000,
  },
  {
    id: 9,
    src: require('../images/thums up.jpg'),
    name: 'Thums Up',
    price: 'INR 90',
    image: '../images/thums up.jpg',
    category: 'covid',
    description: 'Thumsup Diet Can (300 ml)',
    discount_price: 2000,
  },
  {
    id: 10,
    src: require('../images/CokeCan.jpg'),
    name: 'COKE',
    price: 'INR 35',
    image: '',
    category: 'covid',
    description: 'Coca-Cola Diet Can (300 ml)',
    discount_price: 2000,
  },
  {
    id: 11,
    src: require('../images/pepsi.jpg'),
    name: 'pepsi',
    price: 'INR 40',
    image: '',
    category: 'covid',
    description: 'Pepsi Can (300 ml)',
    discount_price: 2000,
  },
  {
    id: 12,
    src: require('../images/frooty.jpg'),
    name: 'Fruity',
    price: 'INR 35',
    image: '',
    category: 'covid',
    description: 'Fruity Can (300 ml)',
    discount_price: 2000,
  },
  {
    id: 13,
    src: require('../images/slice.jpg'),
    name: 'Slice',
    price: 'INR 35',
    image: '',
    category: 'covid',
    description: 'Slice Can (300 ml)',
    discount_price: 2000,
  },
  {
    id: 14,
    src: require('../images/maaza.jpg'),
    name: 'Maaza',
    price: 'INR 95',
    image: '',
    category: 'covid',
    description: 'Maaza Bottle (2 litres)',
    discount_price: 2000,
  },
  {
    id: 15,
    src: require('../images/red bull.jpg'),
    name: 'Red bull',
    price: 'INR 50',
    image: '',
    category: 'covid',
    description: 'Redbull Can (300 ml)',
    discount_price: 2000,
  },
  {
    id: 16,
    src: require('../images/energy drinks.jpg'),
    name: 'Energy drinks',
    price: 'INR 60',
    image: '',
    category: 'covid',
    description: 'Energy drinks Can (300 ml)',
    discount_price: 2000,
  },
];

export { products };
